import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Take it to the NEXT level</h1>
        <b>Powered by npx-create-next-app</b>
        <hr />
        {/* Dynamic routing based off Link component */}
        <div>
          <Link href='/movies'>
            <a>Movie List</a>
          </Link>
        </div>
      </div>
    </div>
  )
}
